cozy/cozy-doctypes

com.omdbapi.img/request
org.musicbrainz.release-group/request
org.musicbrainz.release/request
org.wikidata.wbsearchentities/request
org.wikimedia.uploads/request
org.wikipedia.en.api.parse.images/request
org.wikipedia.en.api.query.imageinfo/request
org.wikipedia.en.api/request
org.wikipedia.fr.api.parse.text/request
org.wikipedia.fr.api/request

Removed wikimedia uploads, as indeterminate path length can't be used anymore ( '/' is escaped automatically)

Update remotes doctypes for LMDMF since cozy-stack PR857

---

docs/README.md
docs/io.cozy.contacts.md

Here is a proposal for contacts. Nothing definitive, but I wish to dray your attention to the `_cozy` attribute I proposed. My reasoning is that a field for a Cozy instance is not standard in any way (think vCard), so it's probably better to flag it as non standard. vCard use X- attributes, but I thought a underscore is a better alternative.

io.cozy.contacts doctype proposal

---

docs/io.cozy.contacts.md

Field names that start with _ are reserved by CouchDB

Fix the cozy field name for contacts

---

docs/io.cozy.bank.md

The bank application uses links operations to accounts like this

fix: account identifier in bank operation

---

docs/README.md

The file it was linked to was no longer available in the trunk

Remove settings from README.md

---

docs/io.cozy.bills.md

`groupAmount` is used to match credit operations to a bundle refund that result in a larger bank transaction.

feat: add groupAmount to bills

---

docs/io.cozy.contacts.md

`birthday` and `note` are obviously optionnal fields and should have been from the start.
`email` was the only mandatory field because contacts were coming from sharings. However now that we have a contacts app, we can totally have a contact with no email.

Make all contact fields optionnal

---

docs/io.cozy.bank.md
docs/io.cozy.bills.md

- Change le format pour être plus lisible : 
- `champ`: {type} - Majuscule
---
- io.cozy.bank.operations : 
- bills -> billIds changement de format pour un tableau d'ids
- reimbursements -> operationIds ajout des liens entre les crédits et les débits
---
- io.cozy.bills
- invoice -> invoiceIds + changement de format en tableau d'ids
- originalOperation -> operationIds ajout des liens vers les opérations de crédits et de débits

Update bank doctypes

---

docs/io.cozy.bank.md

We decided to remove this `$` since it's a pain to make queries with it.

fix: remove $ on io.cozy.bank.balancehistories relationships property

---

docs/io.cozy.bank.md

This adds the `localCategoryId` and `localCategoryProba` properties on the `io.cozy.bank.operations` doctype. These properties are introduced in https://github.com/cozy/cozy-banks/pull/290

docs: Add localCategoryId and localCategoryProba

---

cc.cozycloud.autocategorization/request
docs/README.md
docs/cc.cozycloud.autocategorization.md

Add the remote doctype used to send categorized transactions to the auto categorization API.

feat: Add autocategorization remote doctype

---

docs/io.cozy.contacts.md

Change how contacts reference their groups. It now conforms to the standard way to link documents in Cozy

Doc: Update links between contacts and groups

---

docs/io.cozy.bills.md

This PR adds the payslips to the io.cozy.bills doctype. This is not a bill but we aggreed to use this
doctype more like a transaction metadata doctype. Then here it is.
I think the `payslip` attribute is better and using the `invoice` attribute for the associated file would
be very weird. Maybe a more generic `file` or `document` attribute ?

feat: bill pay type

---

docs/README.md
toc.yml

Doc for payslips has been removed. This makes the documentation build [fail](https://travis-ci.org/cozy/cozy.github.io/builds/465282168#L606). This PR removes the references to the payslip doctype.

fix: Remove payslip reference

---

docs/io.cozy.bills.md

After discussing with Thomas and Mathieu, we found out that the `type` property is actually not mandatory on the io.cozy.bills doctype.

fix(bills): Type is not mandatory

---

docs/io.cozy.terms.md

Will be used by the Store to save the accepted terms on application install (if the application has terms)

Add terms doctype

---

docs/README.md

- add `metadataVersion` field to `cozyMetadata`
- update `updatedByApps` to match the new format (see: https://github.com/cozy/cozy-libs/pull/302)

Update cozyMetadata in README

---

docs/io.cozy.contacts.md

- `company` field was missing in `io.cozy.contacts`
- we previously removed `metadata` field from spec (in https://github.com/cozy/cozy-doctypes/commit/95bf4142280024d6d314b507e718bbcbd7762dd0 ) but in the end it has been kept during migration

Fix contact metadata

---

docs/io.cozy.contacts.md

[Context for this change here](https://github.com/konnectors/toutatice/pull/23#issuecomment-483149685).
This makes `lastSync` a bit like `updatedByApps`, but otherwise we would need to constantly update contacts only to update this field, which is a lot of queries for no good reason.

Clarify io.cozy.contacts.sync.lastSync field

---

docs/io.cozy.konnectors.md

- Adds allowed values for the frequency attribute, found in [cozy-home/ducks/triggers/index.js](https://github.com/cozy/cozy-home/blob/master/src/ducks/triggers/index.js#L4)

Clarify frequency attribute in docs/io.cozy.konnectors.md

---

cc.cozycloud.sentry/request

The Sentry API does not accept receiving auth data in both query string
and HTTP headers. Using HTTP headers is recommended by Sentry, so we use
it. See
https://docs.sentry.io/development/sdk-dev/overview/#authentication for
more informations.

fix: Remove query string in cc.cozycloud.sentry

---

docs/io.cozy.contacts.md

Change to 4 space indentation lists to make lists corrects at docs.cozy.io and not only github.

fix(Contacts): Correct identation that break list on docs.cozy.io

---

docs/io.cozy.bank.md

This new `io.cozy.bank.accounts.stats` property will store the average fixed charges for a given account on the reference period.

docs: Add fixedCharges to io.cozy.bank.accounts.stats

---

docs/io.cozy.bills.md

This will be used by the bank service to match bills with bank operations in a bill by bill way.
This will also allow to handle cases where bank operations have very specific labels (ex: payslips)

Add matchingCriterias attribute to bills.

---

docs/README.md
toc.yml

---
Added missing links from Readme.md to toc.yml

docs: Add links to toc.yml

---

docs/io.cozy.apps.md

Current link is redirecting to a 404.

doc: Fix link to io.cozy.app attributes

---

docs/io.cozy.sharings.md

In `io.cozy.sharings`, the `owner` property is never `false`. It is `true` for the document on the cozy of the sharer or absent on the other cozy instance.

Precision for owner in io-cozy-sharings

---

docs/README.md
docs/com.bitwarden.ciphers.md
docs/com.bitwarden.folders.md
toc.yml

Add the doctypes for bitwarden (ciphers and folders)

---

docs/io.cozy.apps.suggestions.md

We want a new reason for suggesting an app: from a matching cipher has been found

docs: Add suggestion reason

---

docs/io.cozy.accounts.md

See https://github.com/cozy/cozy-doctypes/blob/master/docs/README.md#external-relationships

docs: Use correct format for vaultCipher relationship

---

docs/io.cozy.accounts.md

We are going to add a feature on the homepage where konnector errors can be muted. The konnector will still be shown as "errored", but the error message won't be highlighted. 
We only want to mute the specific type of error that is displayed, and in case the problem is muted, fixed and then occurs again, we want to highlight the error again.  
This is why we store 2 things, the error code and the last successful run at the time of the mute. If the same error is detected but the `lastSuccessDate` is older than the `last_success` field of [the trigger's `current_state`](https://docs.cozy.io/en/cozy-stack/jobs/#get-jobstriggers), we need to highlight the error again.
Let me know what you think and if you see a better way to store this info.

Add discardedErrors to triggers

---

docs/io.cozy.accounts.md

In https://github.com/cozy/cozy-doctypes/pull/119 we wrongly introduced
an array in io.cozy.account's vaultCipher relationships. This could let
somebody think that an account can have a relationship to multiple
ciphers, which is not the case. Since an account can only be linked to
one cipher, the value of `relationships.vaultCipher.data` should be an
object.

docs: Update account's vaultCipher relationships format

---

docs/io.cozy.files.md

We want to use shortcuts/hyperlinks to make possible to have files thatare linked to a resource. The resource can be on the same cozy (internal link), on an external site (like wikipedia URL), or linked to a sharing.

docs: Add the shortcut type of files

---

docs/io.cozy.contacts.md

Add `index` and `displayName` to Contacts doctypes.
- `index` is used to sort contacts by specific rules : it's a concatenation of `givenName+familyName+email+cozyUrl`
- `displayName` is the resulted name to show for a contact : it's in order of priority the `givenName` or  `familyName` or `email` or `cozyUrl`
Words `index` (or `sortBy` ?) and `displayName` could be challenged.

fix: Add new doctypes for Contacts

---

docs/io.cozy.bank.md

We need to link io.cozy.bank.accounts to the io.cozy.accounts that was used to fetch the data.
I used the word "connection" so that we do not get confused between the original io.cozy.bank.accounts doc (which is an "account") and the "io.cozy.accounts". The choice of wording here is important since it should be used for other type of "contracts" that will be editable through Harvest, so if you have any qualms about this, please say so.

docs: Add relationships.connection for io.cozy.bank.accounts

---

docs/io.cozy.files.md

docs: io.cozy.files thumbnails links validity

---

docs/io.cozy.accounts.md

As we rely on `account_type` to know which konnector is linked to an account, there is no reason yet to mark it as deprecated, even though we expect to use a relationship in the future.

docs: Remove deprecated mention for account_type

---

docs/io.cozy.contacts.md

docs: fix typo in contact doctype

---

docs/io.cozy.todos.md

This is required by the GL that needs to explain the items labels.

docs: Add item description

---

docs/io.cozy.sharings.md

This doc was not rendered correctly on docs.cozy.io. When adding a new list level, we must use a different bullet character.

fix: Markdown formatting

---

docs/com.bitwarden.ciphers.md

This field was introduced to soft delete / restore ciphers

docs: Add deletedDate field

---

docs/io.cozy.contacts.md

Birthcity and nationalities are added for legal reasons inside io.cozy.identities.

feat: Add birthcity and nationalities

---

docs/README.md
docs/io.cozy.files.md

This doctype is introduced in the qualification migration service in Drive https://github.com/cozy/cozy-drive/pull/2152

docs: Add the io.cozy.files.settings doctype

---

org.mps.store/request

Add specific doctype for Grand Lyon utilisation. 
- compose of API url of GL backend 
- user secret_token Authorization
Note: the domain mentionned is set for recette environment for the moment.

add specific doctype for Grand Lyon - request backend grand lyon

---

docs/io.cozy.files.md

We use this medata.icon to display few shortcuts on the Home's app. Let's document it

docs: Shortcut add icon metadata

---

com.budgetinsight.maifsandbox.api/request

Allows to get a token from BI (with the secrets of the stack).
It will be used for the API PAY (transfer) via Banks App.

feat: Add remote doctype for BI maif sandbox

---

docs/README.md
docs/io.cozy.files.md

This doctype will be useful for incoming client-side encryption in Drive

feat: Add io.cozy.files.encryption doctype

---

docs/README.md
docs/io.cozy.bank.md

Few doctypes were missing: 
- io.cozy.bank.groups
- io.cozy.bank.recipients 
I tried to document them, don't hesitate to complete

docs: Update io.cozy.bank.*

---

docs/io.cozy.files_metadata.md

Adding link to send user to the generic model examples & documentation

docs: adding link for generic model

---

eu.mycozy.dacc/request

No documentation for this remote doctype as there is no documentation for the other dacc remote doctypes.

feat: Add client-dedicated DACC server remote doctype

---

docs/io.cozy.timeseries.md

The CoachCO2 README describes the GeoJSON received from Tracemob. We add a link as a possible (but possibly not unique) geoJSON example.

docs: Add link for GeoJSON example

---

cc.cozycloud.errors/request

Nous avons migré de serveur sentry. Il est nécessaire d'ajouter un remote doctype pour la nouvelle url

feat: Add cc.cozycloud.errors remote doctype

---

docs/com.bitwarden.ciphers.md
docs/com.bitwarden.contacts.md
docs/com.bitwarden.organizations.md
toc.yml

Those doctypes are used to manage organization and share ciphers with
other users :
- com.bitwarden.organizations
- com.bitwarden.contacts
Also `com.bitwarden.ciphers` has been completed with organization
related attributes

docs: Add Bitwarden sharing related doctypes

---

cc.cozycloud.dacc.dev_v2/request
cc.cozycloud.dacc_v2/request
eu.mycozy.dacc_v2/request

This is useful to be able to query any DACC path, without breaking the
existing services using `cc.cozycloud.dacc`, `cc.cozycloud.dacc.dev`, `eu.mycozy.dacc`.
Eventually, those remote-doctypes will be removed
Note this discards https://github.com/cozy/cozy-doctypes/pull/201/files

feat: Add new DACC remote-doctype

---

docs/io.cozy.contacts.md

Update of the `io.cozy.contacts` doc, with the addition of the new address attributes.
See: https://github.com/cozy/cozy-contacts/pull/920

docs: Update contacts address fields

---

docs/io.cozy.settings.md

I will also add in a next PR the 'io.cozy.home.settings' doctype.

docs: Add default redirection in instance settings

---

docs/io.cozy.bank.md

Il manque plusieurs entrées dans le doctype `io.cozy.bank.settings`, je n'ai pas toutes les infos/le temps de les renseigner ici

docs(io.cozy.bank): Add bank settings informations

---

docs/io.cozy.konnectors.md
docs/io.cozy.triggers.md

As [Cozy-Collect](http://github.com/cozy/cozy-collect/) redirects to [Cozy-Home](http://github.com/cozy/cozy-home/), I've changed the naming for greater consistency

fix: Replace cozy-collect by cozy-home

---

pull_request_template.md

We need to update cozy-client when we add a new doctype

docs: Add cozy-client when we add a new doctype

---

docs/io.cozy.files_metadata.md

This PR adds a new metadata attribute named `taxNumber`. It is the fiscal reference number scraped from the taxes pdfs

[SCR-236] docs: Add 'taxNumber' new metadata attribute

---

docs/io.cozy.home.settings.md

This will handle the new fields used for home layout.

Update io.cozy.home.settings doctype VO-990

---

docs/README.md
docs/io.cozy.calendar.md
docs/io.cozy.timeseries.md
toc.yml

Added the `io.cozy.calendar` doctype and added `io.cozy.timeseries.grades` to the timeseries doctype as this is required for [Pronote konnector](https://github.com/konnectors/pronote).
> **Note**
> Needs merging of https://github.com/cozy/cozy-store/pull/916
> **Note**
> Needs merging of https://github.com/cozy/cozy-client/pull/1515
> **Note**
> Needs merging of https://github.com/cozy/cozy-stack/pull/4452

feat: Addition of calendar and grades timeseries doctype

---

cc.cozycloud.announcements.uploads/request
cc.cozycloud.announcements/request
docs/io.cozy.home.settings.md

**Related PRs :**
- https://github.com/cozy/cozy-stack/pull/4462
- https://github.com/cozy/cozy-client/pull/1530
- https://github.com/cozy/cozy-store/pull/920

[VO-1068] feat: Add announcements production server

---

docs/README.md
docs/io.cozy.ai.chat.conversations.md
toc.yml

docs: Add the io.cozy.ai.chat.conversations doctype

---

org.letsgone.api/request

fix letsgone remote doctype

---

docs/io.cozy.files.md

Ref: https://github.com/cozy/cozy-drive/pull/3310

docs(io.cozy.files): Add `hideOOEditTooltip` attribute

---

docs/io.cozy.settings.md

The phone_number field has been added to the io.cozy.settings.instance doctype to store user's phone number for profile information.
Relates to the implementation in profile view where users can now add their phone number to their Cozy profile.

docs: Add phone_number field to instance settings doctype
