cozy/cozy-doctypes

docs/README.md

my best PR

---

com.omdbapi.img/request

O fetch film and tvseries poster img from omdb.com API.
Used in La Musique de Mes Films app.

Add omdb poster api remote doctype.

---

docs/README.md
docs/io.cozy.bills.md

Partial description, I am not knowledgeable on all the fields, but it's a start.

feat: add io.cozy.bills doctype

---

docs/io.cozy.bills.md

I am almost sure the wording is not good but that is the best I can do...

feat: added isThirdPartyPayer in io.cozy.bills

---

docs/README.md
docs/io.cozy.accounts.md

This PR is in WIP as we need to extract `accountName` from the `auth` attributes and rename it `label`.

docs: add io.cozy.accounts 📚

---

com.googleapis.maps/request

add google maps api doctype

---

docs/README.md
docs/io.cozy.payslips.md
toc.yml

This is a first proposal for the doctype regarding payslips which will be used at the moment by payfit, cesu and pajemploi connectors and also should be handled by cozy-konnector-libs `linkBankOperations`.
Please help me regarding the choosing of the good terms and for english vocabulary in general.

feat: add io.cozy.payslips

---

package.json
src/BankAccount.js
src/BankTransaction.js
src/Document.js
src/index.js
src/log.js
src/models.spec.js
src/utils/BankingReconciliator.js
src/utils/BankingReconciliator.spec.js
src/utils/__snapshots__/BankingReconciliator.spec.js.snap
yarn.lock

Bug fixes and improvements discovered while integrating with the credit
agricole konnector.

reconciliator improvements

---

src/BalanceHistory.spec.js
src/Document.js
src/Document.spec.js

According to the idAttributes of a Document, it is possible to delete
all duplicates.

feat: delete duplicates

---

docs/io.cozy.accounts.md

Add doc about namePath and other fields declared in `manifest.konnector`

More detail about auth

---

docs/README.md
docs/com.unibet.bets.md

I'm not sure of this documentation. But seems to be the right place.

feat: add com.unibet.bets doctype in documentation

---

cc.cozycloud.autocategorization/request

It was on a dev URL for tests. It is ready for prod now, so we update the URL.

feat: Update cc.cozycloud.autocategorization to prod URL

---

docs/README.md

- relationships
- cozyMetadata

feat: Generic schema of a document

---

docs/io.cozy.contacts.md

Add cozyMetadata and accounts relationships to io.cozy.contacts doctype

feat: Update io.cozy.contacts doctype

---

docs/io.cozy.contacts.md

feat: Add me field to io.cozy.contacts doc

---

docs/io.cozy.apps.suggestions.md

Add documentation for the new `io.cozy.apps.suggestions` doctype.

feat: Add io.cozy.apps.suggestions

---

docs/io.cozy.contacts.md

See https://github.com/cozy/cozy-libs/pull/400

fix(Contacts): trashed is not required for contacts and groups

---

docs/io.cozy.accounts.md

Two new attributes: `state` and ~~`twofa_code`~~ `twoFACode`.

Update io.cozy.accounts docs with 2FA

---

docs/README.md
docs/io.cozy.procedures.md

Add `io.cozy.procedures.administrative` doctype

doc: Add io.cozy.procedures doctype

---

docs/io.cozy.files.md

Fix identation in io.cozy.files

fix: Fix bullet point identation in io.cozy.files

---

docs/io.cozy.bank.md

This is the first draft for the new `io.cozy.bank.accounts.stats` that will store aggregated data for each `io.cozy.bank.accounts`.
To give some context: this doctype will be created by a cozy-banks' service that will analyze the transactions of each accounts on the last 3 months. And it will be read to feed the credit file automatically.

docs: Add io.cozy.bank.accounts.stats

---

docs/io.cozy.apps.md

We forgot to add document about those specials use cases.

docs: Add documentation about magic folder

---

docs/README.md

Added a introduction to doctypes. If you know other documentations that could be linked for further reading, please tell me.

Introduction to doctypes

---

docs/io.cozy.accounts.md

`BaseKonnector:waitForTwoFaCode` can set those status.

docs: Add types of TWO_FAS

---

.github/auto-merge.yml

PRs with label `automerge` and with at least 1 approval will get automerged by probot-automerge.

feat: Configure automerge

---

docs/README.md
docs/io.cozy.accounts.md

Description needs some more work.

Add accounts vault cipher relationship

---

docs/io.cozy.settings.md

Add doc about the bitwarden settings doc

---

docs/README.md
toc.yml

Doc was existing but was not linked
- TOC
- README

docs: Add apps suggestions links

---

docs/io.cozy.accounts.md

Fix the parent relationship example

---

docs/README.md
toc.yml

docs: Remove two duplicates in toc.yml

---

docs/README.md
docs/io.cozy.notes.md
toc.yml

docs: Add documentation about the io.cozy.notes doctypes

---

docs/io.cozy.bills.md

This adds the recurring attribute to io.cozy.bills

feat: add recurring bills

---

docs/io.cozy.bank.md

Mentions two important attributes of bank accounts and bank transactions.

docs: Add mention of vendorId and vendorAccountId

---

docs/README.md

- Display the name of the doctype directly in the readme
- Also list "sub doctypes"

feat: Display the doctype name in the readme

---

docs/io.cozy.files.md

Add a link to the full description

feat: Link to file metada

---

docs/io.cozy.accounts.md

- Reorder sections
- Add information on the `contracts` relationship

docs: Improve io.cozy.accounts doctype doc

---

docs/io.cozy.sharings.md

docs: Add values for member.status

---

docs/io.cozy.files_metadata.md

This reflects the qualification changes introduced by https://github.com/cozy/cozy-client/pull/820 and https://github.com/cozy/cozy-drive/pull/2152

docs: New qualification format

---

docs/io.cozy.bank.md

Added latestDate and accounts to the io.cozy.bank.recurrence doctype.

feat: Update io.cozy.bank.recurrence

---

docs/io.cozy.sharings.md

Fix io.cozy.sharings doc indentation

---

docs/io.cozy.files.md
docs/io.cozy.files_metadata.md

feat: add carbonCopy and electronicSafe

---

docs/io.cozy.contacts.md

following the addition of the birth country field in edit personal info (cozy-banks)

feat: Add birthcountry field

---

docs/io.cozy.photos.md

Some settings changed after some improvements in the clustering service

docs: Update clustering settings

---

docs/README.md
docs/io.cozy.timeseries.md
toc.yml

The time series doctype will be used to store any kind of time series,
such as temperature, geojson, sport activities, etc.

docs: Add time series doctype

---

docs/io.cozy.sharings.md

docs: Add initial_sync / shortcut_id and initial_number

---

cc.cozycloud.dacc-dev/request
cc.cozycloud.dacc/request

The DACC (Data Aggregator Cross Cozy) will be used to perform
aggregation from anonymized measures.

feat: Add remote doctypes for DACC

---

org.ecolyo.dju/request

Added a remote doctype for the datagrandlyon API in order to gather data about temperatures and Dju.

Add ecolyo remote doctype for temperatures and dju data

---

docs/README.md

docs: Fix mardown issue

---

docs/io.cozy.bank.md

A mergé après https://github.com/cozy/cozy-banks/pull/2255

docs: Add `latestAmount` in io.cozy.bank.recurrence

---

org.ecolyo.backoffice.partners.info.rec/request
org.ecolyo.backoffice.partners.info/request

feat: Add backfoffice partners issue remote doctypes for rec and prod

---

org.ecolyo.backoffice.prices.rec/request
org.ecolyo.backoffice.prices/request

feat: Add remote doctypes for ecolyo backoffice prices rec and prod

---

docs/README.md
docs/io.cozy.notes.md

Add some doc so we don't forget its existence

docs: Add io.cozy.notes.images doctype

---

org.mps.registry.rec/request
org.mps.registry/request

feat(mps): add registry remote doctypes

---

docs/io.cozy.identities.md

This updates the io.cozy.identities doctype with the latest improvements

docs: Update io.cozy.identities

---

docs/README.md
docs/io.cozy.tags.md
toc.yml

PR associées à la création du nouveau doctype : 
- https://github.com/cozy/cozy-store/pull/801
- https://github.com/cozy/cozy-stack/pull/3470

feat: Add io.cozy.tags

---

docs/io.cozy.bank.md

English spelling

---

docs/io.cozy.files_metadata.md

Add few informations about Note's metadatas
~~- [ ] in the `Readme.md` index page~~
~~- [ ] in the `toc.yml` page~~
~~- [ ] https://github.com/cozy/cozy-store/blob/master/src/locales/en.json~~
~~- [ ] https://github.com/cozy/cozy-store/blob/master/src/config/permissionsIcons.json~~
~~- [ ] https://github.com/cozy/cozy-store/tree/master/src/assets/icons/permissions~~
~~- [ ] https://github.com/cozy/cozy-stack/blob/master/assets/locales/en.po~~
~~- [ ] https://github.com/cozy/cozy-stack/blob/master/assets/styles/cirrus.css~~

feat: Add Note metadata

---

docs/io.cozy.apps.suggestions.md

To explain that Cozy-Pass also store data in this doctype

docs: Update apps.suggestions

---

docs/io.cozy.accounts.md

Linxo connectors are not relevant anymore

feat: Update io.cozy.accounts for BI connectors

---

com.inokufu.api/request
com.mega-apply.dev/request
com.megaapply.dev/request
com.megaapply.www/request
io.vision.palm-app/request

fix: Remove faulty remote doctype mega-apply and palm-app
feat: Add more query param options to com.inokufu.api

fix: Switch mega apply to production endpoint

---

org.ecolyo.backoffice.custom.popup.rec/request
org.ecolyo.backoffice.custom.popup/request

feat: Add custom popup remote doctypes

---

docs/io.cozy.accounts.md

Adding some undocumented possible attributs for io.cozy.accounts

docs: Enhance io.cozy.accounts doc

---

docs/io.cozy.files.md

feat: Add icon and iconMimetype in shortcuts

---

docs/README.md
docs/io.cozy.home.settings.md
toc.yml

https://github.com/cozy/cozy-store/pull/855
https://github.com/cozy/cozy-stack/pull/3865

feat: Add io.cozy.home.settings

---

org.ecolyo.dju_v2/request

new dju endpoint

---

docs/io.cozy.settings.md

relative to https://github.com/cozy/cozy-store/pull/862

docs: Add docs for io.cozy.settings.display

---

com.budgetinsight.maifsandbox.api/request

- [N/A] in the `Readme.md` index page
- [N/A] in the `toc.yml` page
- [N/A] https://github.com/cozy/cozy-store/blob/master/src/locales/en.json
- [N/A] https://github.com/cozy/cozy-store/blob/master/src/config/permissionsIcons.json
- [N/A] https://github.com/cozy/cozy-store/tree/master/src/assets/icons/permissions
- [N/A] https://github.com/cozy/cozy-stack/blob/master/assets/locales/en.po
- [N/A] https://github.com/cozy/cozy-stack/blob/master/assets/styles/cirrus.css

Remove old maif stuff

---

docs/io.cozy.files_metadata.md

docs(Files): Add additional metadata

---

docs/io.cozy.contacts.md

docs: Add id and geo on contact address

---

docs/io.cozy.timeseries.md

docs: Add title docs on timeseries

---

docs/README.md
docs/io.cozy.coachco2.md
toc.yml

docs: Add io.cozy.coachco2.settings

---

docs/io.cozy.files_metadata.md

The relationship does not belong here

docs: Remove relationship from metadata

---

org.ecolyo.dju_v3/request

feat: new dju api

---

org.ecolyo.avg-temperature/request

feat: new avg-temperature api

---

docs/README.md
docs/io.cozy.remote.nextcloud.files.md
toc.yml

docs: Add the io.cozy.remote.nextcloud.files doctype

---

cc.cozycloud.announcements.dev.uploads/request
cc.cozycloud.announcements.dev/request
docs/README.md
docs/cc.cozycloud.announcements.md
docs/io.cozy.home.settings.md
toc.yml

**Related PRs:**
- https://github.com/cozy/cozy-store/pull/919
- https://github.com/cozy/cozy-client/pull/1523
- https://github.com/cozy/cozy-stack/pull/4458

[VO-710] docs: Add announcements
